# Generated by Django 5.0 on 2023-12-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('date_of_birth', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('place_of_stay', models.CharField(max_length=255)),
                ('previous_experience', models.TextField()),
                ('id', models.IntegerField(default=8150467122, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
