# Generated by Django 5.0 on 2023-12-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_user_delete_yourmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(default=6514933779, primary_key=True, serialize=False, unique=True),
        ),
    ]
