# Generated by Django 5.0 on 2023-12-29 01:18

import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=members.models.generate_random_id, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
